/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ClothDeptHeadRole;

import Business.Enterprise.Enterprise;
import Business.Organization.ClothesOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Ankur
 */
public class ClothDeptHeadWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private ClothesOrganization organization;
    /**
     * Creates new form ClothDeptHeadWorkAreaJPanel
     */
    public ClothDeptHeadWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, ClothesOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDonatedProducts = new javax.swing.JButton();
        btnRequestedProducts = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        btnDonatedProducts.setText("Donated Clothes");
        btnDonatedProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonatedProductsActionPerformed(evt);
            }
        });

        btnRequestedProducts.setText("Requested Clothes");
        btnRequestedProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestedProductsActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Clothes Dept Head WorkArea");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRequestedProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDonatedProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel6)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(btnDonatedProducts)
                .addGap(50, 50, 50)
                .addComponent(btnRequestedProducts)
                .addContainerGap(174, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDonatedProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonatedProductsActionPerformed
        DonatedClothesJPanel panel = new DonatedClothesJPanel(userProcessContainer,userAccount, organization,enterprise);
        userProcessContainer.add("DonatedAppliancesJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnDonatedProductsActionPerformed

    private void btnRequestedProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestedProductsActionPerformed
        RequestedClothesJPanel panel = new RequestedClothesJPanel(userProcessContainer,userAccount, organization,enterprise);
        userProcessContainer.add("RequestedClothesJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRequestedProductsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDonatedProducts;
    private javax.swing.JButton btnRequestedProducts;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
