/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ClothDeptHeadRole;

import userinterface.AppliancesDeptHeadRole.*;
import Business.Enterprise.Enterprise;
import Business.Organization.AppliancesOrganization;
import Business.Organization.ClothesOrganization;
import Business.Product.Product;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ankur
 */
public class DonatedClothesJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private ClothesOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form DonatedAppliancesJPanel
     */
    public DonatedClothesJPanel(JPanel userProcessContainer, UserAccount account, ClothesOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
       populateDonatedProductsTable();
    }
    
    private void populateDonatedProductsTable(){
        DefaultTableModel dtm = (DefaultTableModel)ClothesDonationTable.getModel();
        
        dtm.setRowCount(0);
        //Donor donor = (Donor)userAccount.getEmployee();
        /*
        for (Product product: organization.getDonationList().getProductList() ){
            Object[] row= new Object[3];
            row[0]= product.getProductName();
            row[1]= product.getProductDesc();
            row[2]= product.getDonor().getName();
            //order.getSalesPerson().setCommission(order.calculateCommission(orderItem) * orderItem.getQuantity());
            dtm.addRow(row);
        }
        */
        for (Product product: organization.getDonationList().getProductList() ){
            if(product.getProductStatus().equals("In-Process")){
                product.setProductStatus("Received by Clothes Head");
            }
            
            Object[] row= new Object[6];
            row[0]= product.getProductID();
            row[1]= product;
            row[2]= product.getProductDesc();
            row[3]= product.getDonor().getName();
            row[4]= product.getProductStatus();
            row[5]= product.getDonationDate();
            dtm.addRow(row);
        }
        /*
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[4];
            row[0] = request.getProduct().getProductID();
            row[1] = request.getProduct();
            row[2] = request.getProduct().getProductDesc();
            row[3] = request.getProduct().getDonor().getName();
            request.setStatus("Recieved");
            dtm.addRow(row);
        }
        */
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ClothesDonationTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        btnBack.setText("<<  Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        ClothesDonationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tracking Number", "Cloth", "Description", "Donor", "Status", "Donated Date"
            }
        ));
        jScrollPane1.setViewportView(ClothesDonationTable);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Donated Clothes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(222, 222, 222))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBack)
                .addContainerGap(136, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ClothesDonationTable;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
