/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RecipientRole;

import Business.DonationSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DonorOrganization;
import Business.Organization.Organization;
import Business.Organization.RecipientOrganization;
import Business.People.Recipient;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ankur
 */
public class RecipientWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private RecipientOrganization organization;
    /**
     * Creates new form RecipientWorkAreaJPanel
     */
    public RecipientWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, RecipientOrganization organization, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRequestProduct = new javax.swing.JButton();
        btnViewRequestedList = new javax.swing.JButton();
        btnAddRecipientDetails = new javax.swing.JButton();
        btnViewDetails = new javax.swing.JButton();
        btnRaiseNeed = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnAddLifeEvent = new javax.swing.JButton();

        btnRequestProduct.setText("Request Product");
        btnRequestProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestProductActionPerformed(evt);
            }
        });

        btnViewRequestedList.setText("View Requested Products");
        btnViewRequestedList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRequestedListActionPerformed(evt);
            }
        });

        btnAddRecipientDetails.setText("Add Details");
        btnAddRecipientDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRecipientDetailsActionPerformed(evt);
            }
        });

        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        btnRaiseNeed.setText("Raise a new need");
        btnRaiseNeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaiseNeedActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("Recipient Work Area");

        btnAddLifeEvent.setText("Add Life Events");
        btnAddLifeEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLifeEventActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnAddLifeEvent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViewRequestedList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRequestProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddRecipientDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnViewDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRaiseNeed, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(btnAddRecipientDetails)
                .addGap(36, 36, 36)
                .addComponent(btnViewDetails)
                .addGap(42, 42, 42)
                .addComponent(btnRequestProduct)
                .addGap(34, 34, 34)
                .addComponent(btnViewRequestedList)
                .addGap(35, 35, 35)
                .addComponent(btnRaiseNeed)
                .addGap(31, 31, 31)
                .addComponent(btnAddLifeEvent)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestProductActionPerformed
        Recipient recipient= (Recipient) userAccount.getEmployee();
        //Recipient recipient= (Recipient) userAccount.getEmployee();
        if((recipient.getZipcode()==null || recipient.getZipcode().equals(""))
            || (recipient.getName()==null || recipient.getName().equals(""))
            || (recipient.getStreetName()==null || recipient.getStreetName().equals(""))
            || (recipient.getPhoneNumber()==null || recipient.getPhoneNumber().equals(""))
            || (recipient.getCity()==null || recipient.getCity().equals(""))
            || (recipient.getFamilyIncome()==null || recipient.getFamilyIncome().equals(""))
             ){
            JOptionPane.showMessageDialog(null, "Please enter details first");
        }
        else{
        RequestProductJPanel panel = new RequestProductJPanel(userProcessContainer,userAccount, organization,enterprise);
        userProcessContainer.add("RequestProductJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnRequestProductActionPerformed

    private void btnViewRequestedListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRequestedListActionPerformed
        Recipient recipient= (Recipient) userAccount.getEmployee();
        if((recipient.getZipcode()==null || recipient.getZipcode().equals(""))
            || (recipient.getName()==null || recipient.getName().equals(""))
            || (recipient.getStreetName()==null || recipient.getStreetName().equals(""))
            || (recipient.getPhoneNumber()==null || recipient.getPhoneNumber().equals(""))
            || (recipient.getCity()==null || recipient.getCity().equals(""))
            || (recipient.getFamilyIncome()==null || recipient.getFamilyIncome().equals(""))
             ){
            JOptionPane.showMessageDialog(null, "Please enter details first");
        } else {
        ViewRequestedProductsJPanel panel = new ViewRequestedProductsJPanel(userProcessContainer,userAccount, organization,enterprise);
        userProcessContainer.add("ViewRequestedProductsJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnViewRequestedListActionPerformed

    private void btnAddRecipientDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRecipientDetailsActionPerformed
        Recipient recipient= (Recipient) userAccount.getEmployee();
        if(recipient.getZipcode()!=null){
            JOptionPane.showMessageDialog(null, "Recipient already added his/her details");
        }
        else{
        AddRecipientDetailsJPanel panel = new AddRecipientDetailsJPanel(userProcessContainer,userAccount, organization,enterprise);
        userProcessContainer.add("AddRecipientDetailsJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnAddRecipientDetailsActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
    Recipient recipient= (Recipient) userAccount.getEmployee();
        if((recipient.getZipcode()==null || recipient.getZipcode().equals(""))
            || (recipient.getName()==null || recipient.getName().equals(""))
            || (recipient.getStreetName()==null || recipient.getStreetName().equals(""))
            || (recipient.getPhoneNumber()==null || recipient.getPhoneNumber().equals(""))
            || (recipient.getCity()==null || recipient.getCity().equals(""))
            || (recipient.getFamilyIncome()==null || recipient.getFamilyIncome().equals(""))
             ){
            JOptionPane.showMessageDialog(null, "Please enter details first");
        } else {
        ViewDetailsJPanel panel = new ViewDetailsJPanel(userProcessContainer,userAccount, organization,enterprise);
        userProcessContainer.add("ViewDetailsJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnRaiseNeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaiseNeedActionPerformed
        Recipient recipient= (Recipient) userAccount.getEmployee();
        if((recipient.getZipcode()==null || recipient.getZipcode().equals(""))
            || (recipient.getName()==null || recipient.getName().equals(""))
            || (recipient.getStreetName()==null || recipient.getStreetName().equals(""))
            || (recipient.getPhoneNumber()==null || recipient.getPhoneNumber().equals(""))
            || (recipient.getCity()==null || recipient.getCity().equals(""))
            || (recipient.getFamilyIncome()==null || recipient.getFamilyIncome().equals(""))
             ){
            JOptionPane.showMessageDialog(null, "Please enter details first");
        }
        else{
        RaiseANewNeedJPanel panel = new RaiseANewNeedJPanel(userProcessContainer,userAccount, organization,enterprise);
        userProcessContainer.add("RaiseANewNeedJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnRaiseNeedActionPerformed

    private void btnAddLifeEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLifeEventActionPerformed
        Recipient recipient= (Recipient) userAccount.getEmployee();
        if((recipient.getZipcode()==null || recipient.getZipcode().equals(""))
            || (recipient.getName()==null || recipient.getName().equals(""))
            || (recipient.getStreetName()==null || recipient.getStreetName().equals(""))
            || (recipient.getPhoneNumber()==null || recipient.getPhoneNumber().equals(""))
            || (recipient.getCity()==null || recipient.getCity().equals(""))
            || (recipient.getFamilyIncome()==null || recipient.getFamilyIncome().equals(""))
             ){
            JOptionPane.showMessageDialog(null, "Please enter details first");
        }
        else{
        AddLifeEventsJPanel panel = new AddLifeEventsJPanel(userProcessContainer,userAccount, organization,enterprise);
        userProcessContainer.add("AddLifeEventsJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnAddLifeEventActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLifeEvent;
    private javax.swing.JButton btnAddRecipientDetails;
    private javax.swing.JButton btnRaiseNeed;
    private javax.swing.JButton btnRequestProduct;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JButton btnViewRequestedList;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
