/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RecipientRole;

import userinterface.DonorRole.*;
import Business.Enterprise.Enterprise;
import Business.Organization.DonorOrganization;
import Business.Organization.RecipientOrganization;
import Business.People.Donor;
import Business.People.Recipient;
import Business.UserAccount.UserAccount;
import Business.Utils.MyAddressVerifier;
import Business.Utils.MyIntegerVerifier;
import Business.Utils.MyNameVerifier;
import Business.Utils.MyPhoneNumberVerifier;
import Business.Utils.MyZipCodeVerifier;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ankur
 */
public class ViewDetailsJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private RecipientOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    
    /**
     * Creates new form ViewDetailsJPanel
     */
    public ViewDetailsJPanel(JPanel userProcessContainer, UserAccount account, RecipientOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        populateDonorDetails();
        nameTxt.setEnabled(false);
        phoneNumberTxt.setEnabled(false);
        streetNameTxt.setEnabled(false);
        ageTxt.setEnabled(false);
        cityTxt.setEnabled(false);
        zipcodeTxt.setEnabled(false);
        familyIncomeTxt.setEnabled(false);
        MyAddressVerifier myStringVerifier= new MyAddressVerifier();
        streetNameTxt.setInputVerifier(myStringVerifier);
        MyPhoneNumberVerifier myPhoneNumberVerifier= new MyPhoneNumberVerifier();
        phoneNumberTxt.setInputVerifier(myPhoneNumberVerifier);
        MyNameVerifier myNameVerifier= new MyNameVerifier();
        nameTxt.setInputVerifier(myNameVerifier);
        cityTxt.setInputVerifier(myNameVerifier);
        MyZipCodeVerifier myZipVerifier= new MyZipCodeVerifier();
        zipcodeTxt.setInputVerifier(myZipVerifier);
        MyIntegerVerifier myAgeVerifier= new MyIntegerVerifier();
        ageTxt.setInputVerifier(myAgeVerifier);
        familyIncomeTxt.setInputVerifier(myAgeVerifier);
    }
    
    private void populateDonorDetails(){
        
        //Donor donor = (Donor)userAccount.getEmployee();
        Recipient recipient = (Recipient)userAccount.getEmployee();
        nameTxt.setText(recipient.getName());
        phoneNumberTxt.setText(recipient.getPhoneNumber());
        streetNameTxt.setText(recipient.getStreetName());
        cityTxt.setText(recipient.getCity());
        zipcodeTxt.setText(recipient.getZipcode());
        ageTxt.setText(recipient.getAge());
        familyIncomeTxt.setText(recipient.getFamilyIncome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        streetNameTxt = new javax.swing.JTextField();
        ageTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        phoneNumberTxt = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cityTxt = new javax.swing.JTextField();
        zipcodeTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        familyIncomeTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        streetNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetNameTxtActionPerformed(evt);
            }
        });

        jLabel1.setText("Name");

        jLabel3.setText("Phone Number");

        jLabel4.setText("Street Name");

        jLabel5.setText("Age");

        btnBack.setText("<<  Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel7.setText("City");

        jLabel6.setText("Zip/ Postal Code");

        cityTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTxtActionPerformed(evt);
            }
        });

        jLabel2.setText("Family Annual Income");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("View Recipient Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(45, 45, 45)
                .addComponent(btnUpdate)
                .addGap(53, 53, 53)
                .addComponent(btnSave)
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(familyIncomeTxt))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(phoneNumberTxt)
                                    .addComponent(streetNameTxt)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ageTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(zipcodeTxt)
                                    .addComponent(cityTxt)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(phoneNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(streetNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(zipcodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(familyIncomeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnUpdate)
                    .addComponent(btnSave))
                .addContainerGap(126, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        nameTxt.setEnabled(true);
        phoneNumberTxt.setEnabled(true);
        streetNameTxt.setEnabled(true);
        ageTxt.setEnabled(true);
        cityTxt.setEnabled(true);
        zipcodeTxt.setEnabled(true);
        familyIncomeTxt.setEnabled(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(nameTxt.getText().trim().length()==0
               ||phoneNumberTxt.getText().trim().length()==0
               || streetNameTxt.getText().trim().length()==0
               || cityTxt.getText().trim().length()==0
               || zipcodeTxt.getText().trim().length()==0
               || ageTxt.getText().trim().length()==0
               || familyIncomeTxt.getText().trim().length()==0)
       {
           JOptionPane.showMessageDialog(this, "Please enter all the values.","Error", JOptionPane.ERROR_MESSAGE);
            return;
       }
        
        Recipient recipient = (Recipient)userAccount.getEmployee();
        recipient.setName(nameTxt.getText());
        recipient.setPhoneNumber(phoneNumberTxt.getText());
        recipient.setStreetName(streetNameTxt.getText());
        recipient.setCity(cityTxt.getText());
        recipient.setZipcode(zipcodeTxt.getText());
        recipient.setAge(ageTxt.getText());
        recipient.setFamilyIncome(familyIncomeTxt.getText());
        
        JOptionPane.showMessageDialog(null, "Details updated successfully!!");
    }//GEN-LAST:event_btnSaveActionPerformed

    private void streetNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetNameTxtActionPerformed

    private void cityTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTxt;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField cityTxt;
    private javax.swing.JTextField familyIncomeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField phoneNumberTxt;
    private javax.swing.JTextField streetNameTxt;
    private javax.swing.JTextField zipcodeTxt;
    // End of variables declaration//GEN-END:variables
}
