/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DonorRole;

import Business.Enterprise.Enterprise;
import Business.Organization.DonorOrganization;
import userinterface.AdministrativeRole.*;
import Business.People.Donor;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Utils.MyPhoneNumberVerifier;
import Business.Utils.MyAddressVerifier;
import Business.Utils.MyIntegerVerifier;
import Business.Utils.MyNameVerifier;
import Business.Utils.MyZipCodeVerifier;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Ankur
 */
public class AddDonorDetailsJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private DonorOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form CreateDonorJPanel
     */
    public AddDonorDetailsJPanel(JPanel userProcessContainer, UserAccount account, DonorOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        Donor donor = (Donor)userAccount.getEmployee();
        nameTxt.setText(donor.getName());
        nameTxt.setEnabled(false);
        MyAddressVerifier myStringVerifier= new MyAddressVerifier();
        streetNameTxt.setInputVerifier(myStringVerifier);
        MyPhoneNumberVerifier myPhoneNumberVerifier= new MyPhoneNumberVerifier();
        phoneNumberTxt.setInputVerifier(myPhoneNumberVerifier);
        MyNameVerifier myNameVerifier= new MyNameVerifier();
        nameTxt.setInputVerifier(myNameVerifier);
        cityTxt.setInputVerifier(myNameVerifier);
        MyZipCodeVerifier myZipVerifier= new MyZipCodeVerifier();
        zipcodeTxt.setInputVerifier(myZipVerifier);
        MyIntegerVerifier myAgeVerifier= new MyIntegerVerifier();
        ageTxt.setInputVerifier(myAgeVerifier);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        phoneNumberTxt = new javax.swing.JTextField();
        streetNameTxt = new javax.swing.JTextField();
        ageTxt = new javax.swing.JTextField();
        btnCreateDonor = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cityTxt = new javax.swing.JTextField();
        zipcodeTxt = new javax.swing.JTextField();

        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Donor Registration");

        jLabel3.setText("Phone Number");

        jLabel4.setText("Street Name");

        jLabel5.setText("Age");

        btnCreateDonor.setText("Add Details");
        btnCreateDonor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDonorActionPerformed(evt);
            }
        });

        btnBack.setText("<<  Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel7.setText("City");

        jLabel6.setText("Zip/ Postal Code");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(87, 87, 87)
                                .addComponent(btnCreateDonor))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(zipcodeTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addComponent(cityTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(streetNameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phoneNumberTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ageTxt)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 276, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(phoneNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(streetNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cityTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(zipcodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ageTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateDonor)
                    .addComponent(btnBack))
                .addContainerGap(97, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateDonorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDonorActionPerformed
       //String name = nameTxt.getText();
       String phoneNumber= phoneNumberTxt.getText();
       String address= streetNameTxt.getText();
       String age= ageTxt.getText();
       String city= cityTxt.getText();
       String zip=zipcodeTxt.getText();
       
       Boolean isValidPhoneNumber, isValidAddress, isValidCity, isValidZip, isValidAge;
       /*
       Pattern pattern = Pattern.compile("[1-9]\\d{9}");
       Matcher matcher = pattern.matcher(phoneNumber);
       if (matcher.matches()) {
    	  isValidPhoneNumber = true;
        }
        else
        {
    	  isValidPhoneNumber = false;
        }
       */
       /*
        Pattern patternAddress = Pattern.compile("[0-9][a-zA-Z]");
        Matcher matcherAddress = patternAddress.matcher(address);
        if (matcherAddress.matches()){
            isValidAddress = true;
        }
        else
        {
            isValidAddress = false;
        }
        
        Pattern patternCity = Pattern.compile("[a-zA-Z]+");
        Matcher matcherCity = patternCity.matcher(city);
        if (matcherCity.matches()){
            isValidCity = true;
        }
        else
        {
            isValidCity = false;
        }
        
        Pattern patternZip = Pattern.compile("\\d{5}");
        Matcher matcherZip = patternZip.matcher(zip);
        if (matcherZip.matches()){
            isValidZip = true;
        }
        else
        {
            isValidZip = false;
        }
        
        Pattern patternAge = Pattern.compile("\\d{2}");
        Matcher matcherAge = patternAge.matcher(age);
        if (matcherAge.matches()){
            isValidAge = true;
        }
        else
        {
            isValidAge = false;
        }
        */
        /*if(
        //   || isValidCity== false
            isValidPhoneNumber ==false
        //   || isValidAge ==  false
        //   || isValidZip== false
                ){
            JOptionPane.showMessageDialog(null, "Enter Valid values");
            
        }
        */
       
       if(phoneNumber.trim().length()==0
               || address.trim().length()==0
               || city.trim().length()==0
               || zip.trim().length()==0
               || age.trim().length()==0)
       {
           JOptionPane.showMessageDialog(this, "Please enter all the values.","Error", JOptionPane.ERROR_MESSAGE);
            return;
       }
        
       //Donor donor = new Donor();
       Donor donor = (Donor)userAccount.getEmployee();
       
       //organization.getPersonDirectory().getPersonList().add(donor);
       //donor.setName(name);
       donor.setPhoneNumber(phoneNumber);
       donor.setStreetName(address);
       donor.setCity(city);
       donor.setZipcode(zip);
       donor.setAge(age);
        
       JOptionPane.showMessageDialog(null, "Details added successfully!!");
       
       phoneNumberTxt.setText("");
       streetNameTxt.setText("");
       cityTxt.setText("");
       zipcodeTxt.setText("");
       ageTxt.setText("");
    }//GEN-LAST:event_btnCreateDonorActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTxt;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateDonor;
    private javax.swing.JTextField cityTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField phoneNumberTxt;
    private javax.swing.JTextField streetNameTxt;
    private javax.swing.JTextField zipcodeTxt;
    // End of variables declaration//GEN-END:variables
}
