/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DonorRole;

import Business.Enterprise.Enterprise;
import Business.Organization.AppliancesOrganization;
import Business.Organization.ClothesOrganization;
import Business.Organization.DonorOrganization;
import Business.Organization.MiscOrganization;
import Business.Organization.Organization;
import Business.People.Donor;
import Business.Product.Product;
import Business.UserAccount.UserAccount;
import Business.Utils.MyProductDescVerifier;
import Business.Utils.MyProductVerifier;
import Business.WorkQueue.DonationTestWorkRequest;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ankur
 */
public class NewDonationJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private DonorOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private ArrayList<Product> tempProductList;

    /**
     * Creates new form NewDonationJPanel
     */
    public NewDonationJPanel(JPanel userProcessContainer, UserAccount account, DonorOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        tempProductList = new ArrayList<>();
        populateTypeCombo();
        Donor donor = (Donor)userAccount.getEmployee();
        MyProductVerifier myProdVerifier= new MyProductVerifier();
        productNameTxt.setInputVerifier(myProdVerifier);
        MyProductDescVerifier myProdDescVerifier= new MyProductDescVerifier();
        productDescTxt.setInputVerifier(myProdDescVerifier);
    }

    private void populateTypeCombo(){
        typeComboBox.removeAllItems();
        
        typeComboBox.addItem("Appliances");
        typeComboBox.addItem("Clothes");
        typeComboBox.addItem("Miscellaneous");
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAddToDonationCart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DonationCartJTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox();
        btnBack = new javax.swing.JButton();
        btnSubmitDonation = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        productNameTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        productDescTxt = new javax.swing.JTextArea();

        jLabel1.setText("Type of donation");

        btnAddToDonationCart.setText("Add to Donate");
        btnAddToDonationCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToDonationCartActionPerformed(evt);
            }
        });

        DonationCartJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Item", "Type"
            }
        ));
        jScrollPane1.setViewportView(DonationCartJTable);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Donate Items");

        typeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboBoxActionPerformed(evt);
            }
        });

        btnBack.setText("<<  Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSubmitDonation.setText("Submit Donation");
        btnSubmitDonation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitDonationActionPerformed(evt);
            }
        });

        jLabel3.setText("Product");

        productNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productNameTxtActionPerformed(evt);
            }
        });

        jLabel4.setText("Product Description");

        productDescTxt.setColumns(20);
        productDescTxt.setRows(5);
        jScrollPane2.setViewportView(productDescTxt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(75, 75, 75)
                                .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAddToDonationCart)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(btnBack)
                                    .addGap(112, 112, 112)
                                    .addComponent(btnSubmitDonation))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(120, 120, 120)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(productNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(jLabel2)))
                .addContainerGap(473, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(productNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnAddToDonationCart)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnSubmitDonation))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void typeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboBoxActionPerformed
    //DefaultTableModel model = (DefaultTableModel) ItemsJTable.getModel();
        /*
        model.setRowCount(0);
        if(typeComboBox.getSelectedIndex()==0){
            Object[] row = new Object[1];
            row[0] = "Jeans";
            row[0] = "Shirt";
            row[0] = "Tshirt";
            row[0] = "Socks";
            
            model.addRow(row);
        }
                */
    }//GEN-LAST:event_typeComboBoxActionPerformed

    private void productNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productNameTxtActionPerformed

    private void btnAddToDonationCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToDonationCartActionPerformed
        
        if(productNameTxt.getText().trim().length()==0 
                || productDescTxt.getText().trim().length()==0){
            JOptionPane.showMessageDialog(this, "Please fill all the fields.","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        
        Product product= new Product();
        product.setProductName(productNameTxt.getText());
        product.setProductType(typeComboBox.getSelectedItem().toString());
        product.setProductDesc(productDescTxt.getText());
        //product.setQuantity(Integer.parseInt(quantityTxt.getText()));
        product.setDonor((Donor)userAccount.getEmployee());
        
        tempProductList.add(product);
        
        populateDonationTable();
        
        productNameTxt.setText("");
        productDescTxt.setText("");
        //quantityTxt.setText("");
    }//GEN-LAST:event_btnAddToDonationCartActionPerformed

    private void btnSubmitDonationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitDonationActionPerformed
        Organization org = null;
        Organization org1= null;
        Organization org2= null;
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                       if (organization instanceof AppliancesOrganization) {
                           org = organization;   
                       }
                        if (organization instanceof ClothesOrganization) {
                           org1 = organization;   
                       }
                        if (organization instanceof MiscOrganization) {
                           org2 = organization;   
                       }
                   }
        
        Donor donor = (Donor)userAccount.getEmployee();
        
        for(Product product: tempProductList){
            //DonationTestWorkRequest request= new DonationTestWorkRequest();
        
            //request.setRequestDate(new Date());
            //request.setSender(userAccount);
            //request.setStatus("In-Process");
            //request.setProduct(product);
            product.setProductStatus("In-Process");
            product.setIsDonated("No");
            if(product.getProductType().equals("Appliances")){
             org.getDonationList().getProductList().add(product);
             //org.getWorkQueue().getWorkRequestList().add(request);
            }
            else if (product.getProductType().equals("Clothes")){
             org1.getDonationList().getProductList().add(product);
             //org1.getWorkQueue().getWorkRequestList().add(request);
            }
            else if (product.getProductType().equals("Miscellaneous")){
             org2.getDonationList().getProductList().add(product); 
             //org2.getWorkQueue().getWorkRequestList().add(request);
            }
            Donor d1= null;
            d1=donor;
            d1.getDonationList().getProductList().add(product);
            
            
            
            //userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        
        
        
        //donor.setDonationList();
        
        JOptionPane.showMessageDialog(null, "Thank you for your time and help. We appreciate it");
               
    }//GEN-LAST:event_btnSubmitDonationActionPerformed
    
    private void populateDonationTable(){
        DefaultTableModel dtm = (DefaultTableModel) DonationCartJTable.getModel();
        dtm.setRowCount(0);
        
        for (Product product: tempProductList){
            Object[] row= new Object[2];
            row[0]= product.getProductName();
        //    row[1]= product.getQuantity();
            row[1]= product.getProductType();
            //order.getSalesPerson().setCommission(order.calculateCommission(orderItem) * orderItem.getQuantity());
            dtm.addRow(row);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DonationCartJTable;
    private javax.swing.JButton btnAddToDonationCart;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmitDonation;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea productDescTxt;
    private javax.swing.JTextField productNameTxt;
    private javax.swing.JComboBox typeComboBox;
    // End of variables declaration//GEN-END:variables
}
